version: "3"

networks:
  mainevent:

services:
  eventnode:
    image: srvdocker.lequipe.net/aso/node:12.14.1
    container_name: eventnode
    command: npm start
    stdin_open: true
    tty: true
    working_dir: /var/www/project
    ports:
      - "3000:8080"
    volumes:
      - .:/var/www/project
      - ~/.ssh:/home/node/.ssh:cached
    networks:
      mainevent:
        aliases:
          - "eventnode"

  eventvarnish:
    image: ubuntu-varnish:1.0
    container_name: eventvarnish
    environment:
        - VCL_CONFIG=/var/www/project/varnish.vcl
    volumes:
        - ./varnish.vcl:/var/www/project/varnish.vcl:cached
    ports:
        - "8080:80"
        - "6085:6085"
    networks:
        mainevent:
            aliases:
                - "eventvarnish"

  varnishleaf:
    image: ubuntu-varnish:1.0
    container_name: varnishleaf
    environment:
        - VCL_CONFIG=/var/www/project/varnishleaf.vcl
    volumes:
        - ./varnishleaf.vcl:/var/www/project/varnishleaf.vcl:cached
    ports:
        - "80:80"
    networks:
        mainevent:
            aliases:
                - "varnishleaf"

  varnishleaf1:
    image: ubuntu-varnish:1.0
    container_name: varnishleaf1
    environment:
        - VCL_CONFIG=/var/www/project/varnishleaf.vcl
    volumes:
        - ./varnishleaf.vcl:/var/www/project/varnishleaf.vcl:cached
    ports:
        - "90:80"
    networks:
        mainevent:
            aliases:
                - "varnishleaf1"

